server:
  port: 8080
  rate_limit: 2
  retry_after: 2

  https:
    enable: false
    cert_path: "certs/server/server.crt"
    key_path: "certs/server/server.key"

auth:
  mode: "jwt"
  duration_minutes: 10
  refresh_duration_minutes: 60
  max_refresh_minutes: 144
  signing_algorithm: HS256