package env

const (
	SALT_PASSWORD_ENCRYPT = "SALT_PASSWORD_ENCRYPT"
	SERVER_CONFIG_PATH    = "SERVER_CONFIG_PATH"

	CASBIN_CONFIG_PATH = "CASBIN_CONF_FILE_PATH"
	CASBIN_POLICY_PATH = "CASBIN_POLICY_FILE_PATH"

	JWT_SECRET_ACC  = "JWT_SECRET_ACC"
	JWT_SECRET_REFR = "JWT_SECRET_REFR"
	JWT_ISSUER      = "JWT_ISSUER"

	GOOGLE_CLIENT_ID     = "GOOGLE_CLIENT_ID"
	GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET"

	OAUTH2_USER_INFO_ENDPOINT = "OAUTH2_USER_INFO_ENDPOINT"
	OAUTH2_REDIRECT_URL       = "OAUTH2_REDIRECT_URL"
	OAUTH2_AUTH_URL           = "OAUTH2_AUTH_URL"
	OAUTH2_TOKEN_URL          = "OAUTH2_TOKEN_URL"
)
