package env

const (
	SALT_PASSWORD_ENCRYPT = "SALT_PASSWORD_ENCRYPT"
	SERVER_CONFIG_PATH    = "SERVER_CONFIG_PATH"

	CASBIN_CONFIG_PATH = "CASBIN_CONF_FILE_PATH"
	CASBIN_POLICY_PATH = "CASBIN_POLICY_FILE_PATH"
)
